version: "3.9"
services:
  backend:
    build:
      context: ./PatientService.Api
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  gateway:
    build:
      context: ./Gateway
      dockerfile: Dockerfile
    ports:
      - "7000:80"
    depends_on:
      - backend

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - gateway
